In [1]:
type(numpy)

NameError: name 'numpy' is not defined

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
myarr = np.array(mylist)

In [7]:
myarr

array([1, 2, 3])

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
len(np.linspace(0,10,11))

11

In [22]:
np.random.rand(5,6)

array([[0.45610239, 0.29238715, 0.87832674, 0.91647781, 0.96295813,
        0.15419494],
       [0.68082235, 0.3168797 , 0.54143524, 0.85541221, 0.95057542,
        0.61984823],
       [0.50510412, 0.96428074, 0.9991584 , 0.39447439, 0.15199969,
        0.13914008],
       [0.07048542, 0.97732434, 0.73005755, 0.06067826, 0.61339822,
        0.0090115 ],
       [0.27765595, 0.97849193, 0.55424018, 0.36328385, 0.13407513,
        0.55304622]])

In [26]:
np.random.randint(0,101,(10,9))

array([[58, 25, 21, 21, 98, 34, 23, 82, 86],
       [72, 65, 50, 74, 51, 66, 14, 30, 12],
       [ 6, 21, 51, 35, 87, 34, 93, 39, 98],
       [51, 57, 56, 28, 72, 51, 85, 60, 53],
       [41, 30, 36, 10, 53,  0, 72, 95, 60],
       [44,  1, 38, 97, 18, 36, 30, 83, 23],
       [36, 60, 83, 72, 11, 39, 99, 47, 26],
       [62, 87,  5, 80, 90, 69, 22, 82, 64],
       [25, 44, 98, 65,  5, 84, 62, 13, 19],
       [57, 31, 30, 46, 49, 32, 23, 37, 61]])

In [28]:
np.random.seed(4)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [31]:
ranarr = np.random.randint(0,101,10)

In [30]:
ranarr.max()

99

In [32]:
ranarr.dtype

dtype('int64')

In [34]:
ranarr

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [35]:
ranarr.shape

(10,)

In [49]:
arr = np.random.randint(0,25,25)

In [50]:
arr

array([11,  7, 14,  2, 13, 16,  3, 17,  7,  3,  1,  5, 21,  9,  3, 21, 17,
       11,  1,  9,  3, 13, 15, 14,  7])

In [51]:
arr.shape

(25,)

In [53]:
arr = arr.reshape(5,5)

In [55]:
arr

array([[11,  7, 14,  2, 13],
       [16,  3, 17,  7,  3],
       [ 1,  5, 21,  9,  3],
       [21, 17, 11,  1,  9],
       [ 3, 13, 15, 14,  7]])

In [56]:
arr.shape

(5, 5)

In [57]:
arr.reshape(25,1)

array([[11],
       [ 7],
       [14],
       [ 2],
       [13],
       [16],
       [ 3],
       [17],
       [ 7],
       [ 3],
       [ 1],
       [ 5],
       [21],
       [ 9],
       [ 3],
       [21],
       [17],
       [11],
       [ 1],
       [ 9],
       [ 3],
       [13],
       [15],
       [14],
       [ 7]])

In [58]:
import numpy as np

In [60]:
arr = np.arange(0,11)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr[8]

8

In [63]:
arr[1:5]

array([1, 2, 3, 4])

In [64]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [65]:
arr[0:5] = 100

In [66]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [67]:
arr = np.arange(0,11)

In [68]:
slice_of_array = arr[0:5]

In [69]:
slice_of_array

array([0, 1, 2, 3, 4])

In [70]:
slice_of_array[:] = 99

In [71]:
slice_of_array

array([99, 99, 99, 99, 99])

In [72]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [73]:
arr_copy = arr.copy()

In [74]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [75]:
arr_copy[:] = 100

In [76]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [77]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [79]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [80]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [81]:
arr_2d.shape

(3, 3)

In [85]:
arr_2d[1,1]

25

In [86]:
arr = np.arange(1,11)

In [87]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [89]:
bool_arr = arr>4

In [90]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [91]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [92]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [93]:
arr2 = np.arange(1,11)

In [94]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr2[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [100]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [101]:
dice_rolls

array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6,
       3, 6, 2, 3, 5, 6, 5])

In [104]:
total_over_two = len(dice_rolls[dice_rolls>2])

In [105]:
total_over_two

19

In [106]:
arr = np.arange(0,10)

In [107]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [108]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
arr / arr

/var/folders/9k/jb5h8xsn35v5p5t2k9c8y8q40000gn/T/ipykernel_27421/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [110]:
1 / 0

ZeroDivisionError: division by zero

In [111]:
1 / arr

/var/folders/9k/jb5h8xsn35v5p5t2k9c8y8q40000gn/T/ipykernel_27421/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [112]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [113]:
np.log(arr)

/var/folders/9k/jb5h8xsn35v5p5t2k9c8y8q40000gn/T/ipykernel_27421/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [114]:
arr.std()

2.8722813232690143

In [115]:
arr2d = np.arange(0,25).reshape(5,5)

In [116]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [117]:
arr2d.shape

(5, 5)

In [118]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [119]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

In [120]:
account_transactions

array([ 100, -200,  300, -400,  100,  100, -230,  450,  500, 2000])

In [121]:
account_total = account_transactions.sum()

In [122]:
account_total

2720

In [123]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [124]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [134]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [137]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [139]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [140]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [144]:
np.random.rand(1)

array([0.57044397])

In [145]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [147]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [149]:
np.random.rand(1)

array([0.52083426])

In [150]:
np.random.randn(25)

array([ 0.26348604,  1.64177112,  0.4608163 ,  0.08592347, -1.50995728,
        0.72150246, -0.84341992, -0.51332541, -0.0435368 , -0.27530091,
       -1.56306679, -0.79563099,  0.9305844 ,  0.67776741,  0.69844026,
        0.17360206,  0.66228451,  0.24112216, -0.16820509,  1.16476865,
       -0.24574769, -0.76966777,  1.21217234,  1.2334968 , -1.57415529])

In [153]:
arr = np.arange(1,101)/100

In [154]:
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [155]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [156]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [157]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [158]:
mat[2]

array([11, 12, 13, 14, 15])

In [161]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [162]:
mat[3,4]

20

In [167]:
mat[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [168]:
mat[4]

array([21, 22, 23, 24, 25])

In [169]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [170]:
mat.sum()

325

In [171]:
mat.std()

7.211102550927978

In [172]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])